### ISSUE TITLE
Differences between tinyset and sanitize.css/normalize.css?

### ISSUE THREAD

**Issue by renatonascalves** [danklammer/tinyset#1]
How tinyset is different from normalize.css and [sanitize.css](https://github.com/jonathantneal/sanitize.css)?

**Comment by danklammer** [comment]
@renatonascalves Tinyset is a small utility based framework to jumpstart projects, but does reset and unify some browser style differences.

I placed more attention on larger uniform style issues in different browsers than edge-cases.

If you're worried about all the differences, I recommended still using sanitize.css along with tinyset. I will be adding documentation sooner or later.

**Comment by renatonascalves** [comment]
@danklammer Actually, that was my main concern. I use normalize with sanitize.css, but sanitize states it can be used along side normalize. The same is not very clear with typeset.

Thanks for the feedback though! =)
